#ifdef PL_lang
#define Boiler_And_CO_Temperature "Temperatura Boilera i do CO"
#define Set_Temperature_for_CO_heat "Temperatura do CO USTAW: "
#define Flame_Active_Flame_level "Płomień aktywny. Moc palnika: "
#define Boiler_Active_heat_DHW "Piec w trybie aktywnego podgrzewania CWU wody użytkowej"
#define DHW_HEAT_ON "Podgrzewanie WODY CWU włączone"
#define BOILER_HEAT_ON "Ogrzewanie CO włączone"
#define BOILER_IS_HEATING "Piec w trybie aktywnego grzania CO"
#define DiagMode "Tryb Diagnostyczny"
#define CoolingMode "Tryb Chłodzenia"
#define Second_Engine_Heating_PompActive_Disable_heat "Pompa CO pieca węglowego aktywna -dezaktywuje grzanie;)"
#define Second_Engine_Heating_Water_PompActive "Pompa Wody pieca węglowego aktywna"
#define Update_web_link "Aktualizacja"
#define Web_Serial "Serial Terminal"
#define Boler_mode "Tryb pracy kotła CO:"
#define Automatic_mode "Automatyczny tryb"
#define DHW_Mode "Tryb pracy CWU:"
#define Heating "Grzanie"
#define Off "Wyłączone"
#define DHW_Temp "Temperatura WODY:"
#define DHW_Temp_Set "Temperatura Wody Docel.: "
#define Room_Temp "Temperatura Pokoju"
#define Room_Temp_Set "Temperatura Pokoju Docel.: "
#define Temp_NEWS "Średnia Temperatura Zewnątrz NEWS:"
#define ActualFrom "Aktualne od: "
#define Return_temp "Temperatura Powrotu:"
#define Outside_Cutoff_Below "Temperatura progu grzania CO gdy średnia NEWS: &lt; "
#define msg_Connected "Połączony"
#define msg_disConnected "Rozłączony"
#define Flame_total "Suma mocy płomienia: "
#define Flame_time "Czas pracy płomienia: "
#define t_day "dni"
#define t_hour "godz."
#define t_min "min."
#define t_sek "sek."
#else
#define Boiler_And_CO_Temperature "Boiler And CO Temperature"
#define Set_Temperature_for_CO_heat "Set Temperature for CO heat: "
#define Flame_Active_Flame_level "Flame_Active. Flame level: "
#define Boiler_Active_heat_DHW "Boiler is in Active heat DHW mode"
#define DHW_HEAT_ON "Domestic Hot Water Heat is Enabled"
#define BOILER_HEAT_ON "Boiler Heat for heating is Enabled"
#define BOILER_IS_HEATING "Boiler is Heating"
#define DiagMode "Diagnostic Mode"
#define CoolingMode "Cooling Mode"
#define Second_Engine_Heating_PompActive_Disable_heat "Second Engine Heating Pomp is Active -Disable boiler heat"
#define Second_Engine_Heating_Water_PompActive "Second Engine Water Heating Pomp is Active"
#define Update_web_link "Update"
#define Web_Serial "Web_Serial"
#define Boler_mode "Boiler Mode:"
#define Automatic_mode "Automatic mode"
#define DHW_Mode "Domestic HotWater mode:"
#define Heating "Heating"
#define Off "Off"
#define DHW_Temp "Domestic HotWater Temperature:"
#define DHW_Temp_Set " Domestic HotWater Set:"
#define Room_Temp "Current Room Temp"
#define Room_Temp_Set "Room Temperature SET"
#define Temp_NEWS "Averange NEWS Temperature"
#define ActualFrom "Actual From: "
#define Return_temp "Return Temperature"
#define Outside_Cutoff_Below "Heat Cutoff Temperature when outside NEWS &lt; "
#define msg_Connected "Connected"
#define msg_disConnected "Disconnected"
#define Flame_total "Flame total: "
#define Flame_time "Flame uptime: "
#define t_day "day(s)"
#define t_hour "hour"
#define t_min "min."
#define t_sek "sec."
#endif
